#!/bin/bash

# Exit on any failure
set -e



if [ -z "$AWS_ACCESS_KEY_ID" ]
then
    echo "You must configure AWS_ACCESS_KEY_ID"
    exit 1
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ]
then
    echo "You must configure AWS_SECRET_ACCESS_KEY"
    exit 1
fi


aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
