version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  node:
    docker:
      - image: circleci/node:14.2
    working_directory: ~/repo
  python:
    docker:
      - image: circleci/python:3.7

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  deploy-lambda:
    description: "Deploys application"
    parameters:
      stage:
        type: string
        default: staging
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install serverless CLI
          command: sudo npm i -g serverless
      - run:
          name: Deploy lambda
          command: |
            sls deploy -s <<parameters.stage>>

jobs:
  build_and_test:
    executor: node
    environment:
      NODE_ENV: ci
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo npm i --no-cache git
            sudo npm i

      - run:
          name: Run unit tests
          command: npm run test

      - persist_to_workspace:
          root: ~/repo
          paths: .

  assume-role-staging:
    executor: python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_STAGING

  deploy-staging:
    executor: node
    steps:
      - *attach_workspace

      # - run:
      #     name: Deploy application
      #     command: |
      #       ./node_modules/serverless/bin/serverless deploy -s staging --config serverless.yml
      - deploy-lambda:
          stage: staging

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build_and_test
      - assume-role-staging:
          context: api-assume-role-comino-document-retrieval-staging-context
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - main
      - deploy-staging:
          requires:
            - assume-role-staging
          filters:
            branches:
              only:
                - main
